---@class LeoVimConfig
local M = {
  -- colorscheme can be a string like `catppuccin` or a function that will load the colorscheme
  ---@type string|fun()
  colorscheme = "habamax",
  -- icons used by other plugins
  icons = {
    dap = {
      Stopped = { "󰁕 ", "DiagnosticWarn", "DapStoppedLine" },
      -- Breakpoint = "",
      Breakpoint = "",
      BreakpointCondition = "",
      BreakpointRejected = { "", "DiagnosticError" },
      LogPoint = ".>",
    },
    diagnostics = {
      Error = { name = "DiagnosticSignError", symbol = " " },
      Warn = { name = "DiagnosticSignWarn", symbol = " " },
      Hint = { name = "DiagnosticSignHint", symbol = " " },
      Info = { name = "DiagnosticSignInfo", symbol = " " },
    },
    git = {
      -- added = "",
      -- modified = "",
      -- removed = "",
      LineAdded = " ",
      LineModified = " ",
      LineRemoved = " ",
      FileDeleted = " ",
      FileIgnored = "◌ ",
      FileRenamed = " ",
      FileStaged = "S ",
      FileUnmerged = " ",
      FileUnstaged = " ",
      FileUntracked = "U ",
      Diff = " ",
      Repo = " ",
      Octoface = " ",
      Branch = " ",
      Conflict = " ",
    },
    file = {
      Modified = " ",
      Readonly = "[R]",
      Unnamed = "[No Name]",
      Newfile = "[New]",
    },
    folder = {
      Closed = " ",
      Open = " ",
      Empty = "󰜌 ",
    },
    kinds = {
      Array = " ",
      Boolean = " ",
      Class = " ",
      Color = " ",
      Constant = " ",
      Constructor = " ",
      Codeium = " ",
      Copilot = " ",
      Enum = " ",
      EnumMember = " ",
      Event = " ",
      Field = " ",
      File = " ",
      Files = "󰉓 ",
      Folder = " ",
      Function = "󰊕 ",
      Interface = "󰌗 ",
      Key = "󰌋 ",
      Keyword = " ",
      Method = "m ",
      Module = " ",
      Namespace = " ",
      Null = " ",
      Number = " ",
      Object = " ",
      Operator = "󰆕 ",
      Package = " ",
      Property = " ",
      Reference = " ",
      Snippet = " ",
      String = " ",
      Struct = " ",
      Text = " ",
      TypeParameter = " ",
      StaticMethod = "󰠄 ",
      Symbols = "󰀬 ",
      Git = "󰊢 ",
      Unit = " ",
      Value = "󰎠 ",
      Variable = " ",
    },
    misc = {
      -- Package = "",
      CircuitBoard = " ",
      Clock = " ",
      Robot = "󰚩 ",
      Smiley = " ",
      Squirrel = " ",
      Tag = " ",
      Watch = " ",
    },
    dashboard = {
      Project = " ",
      NewFile = " ",
      RecentFiles = " ",
      FindFile = "󰮗 ",
      FindText = " ",
      RestoreSession = " ",
      Lazy = "󰒲 ",
      Quit = " ",
    },
  },
  non_essential_filetypes = {
    "alpha",
    "dashboard",
    "fugitive",
    "help",
    "NvimTree",
    "neo-tree",
    "neotest-output-panel",
    "neotest-summary",
    "qf",
    "toggleterm",
    "trouble",
  },
  autocompletion = {
    menu = {
      nvim_lsp = "[LSP]",
      spell = "[Spellings]",
      zsh = "[Zsh]",
      buffer = "[Buffer]",
      ultisnips = "[Snip]",
      luasnip = "[Snip]",
      treesitter = "[Treesitter]",
      nvim_lua = "[Lua]",
      path = "[Path]",
      nvim_lsp_signature_help = "[Signature]",
      cmdline = "[Vim Command]",
      codeium = "[Codeium]",
      copilot = "[Copilot]",
    },
  },
}

return M